---
name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.0', '2.1', '2.2' ]
    name: Test on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
      - run: bundle install
      - run: bundle exec rake test
  rubocop:
    runs-on: ubuntu-18.04
    name: RuboCop on Ruby 2.0
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.0
      - run: bundle install
      - run: bundle exec rubocop
